### ISSUE TITLE
Wallet frontend uses relative path to /wallet-api/auth/login

### ISSUE THREAD

**Issue by tdiesler** [walt-id/waltid-identity#1074]
There seems to be a caddy redirect defined to the wallet backend 

```
wallet.local {
    reverse_proxy localhost:7101 # frontend
    reverse_proxy /wallet-api/* localhost:7001 # backend
}
```

AFAIU, this can be problematic in k8s where localhost will not resolve. 
I tried to give explicit redirects to 

* http://wallet-api:7001 # internal endpoint
* http://kubernetes.docker.internal:32001 # external endpoint

Both fail in js with 

```
Could not sign in Error: Invalid reference token: token
    at Yd (uf6SBvNs.js:27:31647)
    at Qd (uf6SBvNs.js:27:33670)
    at async E (7HsHm5Iw.js:1:2617)
```

On k3s, I have an SSL terminating Traefik Ingress like this

```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wallet-demo
  labels:
    app.kubernetes.io/name: wallet-demo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("{{ $.Values.demoWalletHost }}") && PathPrefix("/wallet-api")
      kind: Rule
      services:
        - name: wallet-api
          port: 7001
    - match: Host("{{ $.Values.demoWalletHost }}")
      kind: Rule
      services:
        - name: wallet-demo
          port: 7101
  tls:
    secretName: origin-tls
```

which routes

```
https://wallet.nessus-tech.io/wallet-api => http://wallet-api:7001
```

this only works for proper registered domains (i.e. self signed cert on an IP does not work [I think])

Anyway, is it really necessary that the wallet frontend responds to /wallet-api on the wallet endpoint?
The IngressRoute suggests that it is ok to call the wallet-api directly on it's dedicated endpoint.

With cloud-first, all the various endpoints should be configurable through envars.

As it stands now I cannot run the wallet on local docker-desktop k8s - at least I can't find a way to configure login.

There is also this configuration here 

```
    nitro: {
        compressPublicAssets: {
            gzip: true,
            brotli: false
        },
        devProxy: {
            "/wallet-api/": "${process.env.WALLET_BACKEND_URL}/wallet-api"
        }
    },
```

In k8s there should not be a caddy service imho. Perhaps we can get rid of it in compose too.
