### ISSUE TITLE
crypto-adroid support package for "waltid-crypto" is missing in maven releases.

### ISSUE THREAD

**Issue by i-petkov** [walt-id/waltid-identity#874]
## Describe the bug

`id.walt.crypto:waltid-crypto-android` extension for `id.walt.crypto:waltid-crypto` is not being published in `maven.waltid.dev`

https://maven.waltid.dev/#/releases/id/walt/crypto

## To Reproduce

add waltid libraries to an android project.

```toml
[versions]
waltid = "0.10.0"

[libraries]
waltid-did = { module = "id.walt.did:waltid-did", version.ref = "waltid" }
waltid-sdjwt = { module = "id.walt.sdjwt:waltid-sdjwt", version.ref = "waltid" }
waltid-crypto = { module = "id.walt.crypto:waltid-crypto", version.ref = "waltid" }
waltid-crypto-android = { module = "id.walt.crypto:waltid-crypto-android", version.ref = "waltid" }
waltid-openid4vc = { module = "id.walt.openid4vc:waltid-openid4vc", version.ref = "waltid" }
waltid-verifiable-credentials = { module = "id.walt.credentials:waltid-verifiable-credentials", version.ref = "waltid" }
waltid-verification-policies = { module = "id.walt.policies:waltid-verification-policies", version.ref = "waltid" }
```

```gradle

// settings gradle
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven(url = "https://jitpack.io")
        maven(url = "https://maven.lokalise.com")
        gradlePluginPortal()
        maven("https://maven.waltid.dev/releases")
    }
}


``` gradle
// app level gradle
dependencies {
   ...
    // walt
    implementation(libs.waltid.did)
    implementation(libs.waltid.crypto)
    implementation(libs.waltid.crypto.android)
    implementation(libs.waltid.verification.policies)
    implementation(libs.waltid.openid4vc)
}
```

## Expected behavior

libraries should be downloaded and classes should be added to the project classpath

## Actual behavior

all dependencies, with exception to `libs.waltid.crypto.android` are properly added and accessible in the project.
gradle sync displays error

"Failed to resolve: id.walt.crypto:waltid-crypto-android:0.10.0"

navigating to maven repository: https://maven.waltid.dev/#/releases/id/walt/crypto does not list `crypto-android` package

## Environment

- os version: windows
